### ISSUE TITLE
File Deleted on Restart and OSError: [Errno 1] EPERM

### ISSUE THREAD

**Issue by OwenCrawley** [NStrijbosch/Test#11]
Everytime I try to run a parent file on the spike prime it gives me the error:
`Traceback (most recent call last):  
File "parent_example 1", line 19, in <module>
ImportError: no module named 'hub2hub'`
So then I tried to figure out why it wasn't installing the hub2hub file. I found out that it deleted the file as soon as the program stopped.
I then tried to move the parent code into the installation file and put it after the installation, and get rid of hub.reset() so the program wouldn't stop. I then got this error:
`Traceback (most recent call last): 
  File "Install_hub2hub_v003 1", line 661, in <module> 
  File "hub2hub.py", line 1, in <module>

`OSError: [Errno 1] EPERM` 
I am using Lego Education SPIKE 3.4.3
The Code is attatched
[hub2hub_parent.txt](https://github.com/NStrijbosch/hub-module-notes/files/14747834/hub2hub_parent.txt)

**Comment by OwenCrawley** [comment]
UPDATE: After finding out there is no plans for updating I have switched over to pybricks.com which uses different firmware and as a result still has support.
